[package]
name = "Winu"
version = "0.1.0"
description = "Fantasy Gaming app."
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "Winu"

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"      
chainlink_solana = "1.0.0"
solana-program = "1.18.0"  
